---
_extends: .github

repository:
  name: toxic
  description: An ncurses-based Tox client
  topics: tox, console, chat

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - build
          - build-static
          - bazel-opt
          - Codacy Static Code Analysis
          - code-review/reviewable
          - infer
