name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libraries
        run:
          sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends
            libalut-dev
            libconfig-dev
            libcurl4-gnutls-dev
            libnotify-dev
            libopenal-dev
            libopus-dev
            libqrencode-dev
            libsodium-dev
            libvpx-dev
            python3-dev
            pkg-config

      - name: Install toxcore
        run:
          git clone --depth=1 https://github.com/TokTok/c-toxcore &&
          cd c-toxcore &&
          cmake . -B_build -DBOOTSTRAP_DAEMON=OFF &&
          cd _build &&
          make -j4 &&
          sudo make install

      - name: Build toxic
        run: make -j4
